language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
install:
  - pip install nose_parameterized
  - pip install forseti
  - pip install coveralls
script:
  - nosetests -v --with-coverage
after_success:
  - coveralls